// this this generated by ReactiveDB don't change this file

// route for /app, methods ["get"]
import "./functions/app/index.[get].ts";
// route for /app/:id/add, methods ["post"]
import "./functions/app/$$id/add.[post].ts";
// route for /app/:id/remove, methods ["delete"]
import "./functions/app/$$id/remove.[delete].ts";
// route for /app/:id, methods ["post"]
import "./functions/app/$$id/index.[post].ts";
// route for /, methods ["get"]
import "./functions/index.[get].ts";
// route for /api/data, methods ["post"]
import "./functions/api/data.[post].ts";
// route for /api/users, methods ["get","post","put"]
import "./functions/api/users.[get,post,put].ts";
// route for /data, methods ["get"]
import "./functions/data/index.[get].ts";
// route for /data/name, methods ["post"]
import "./functions/data/name.[post].ts";
// route for /data/yael, methods ["get"]
import "./functions/data/yael.[get].ts";